okteto/remote-kubernetes

- src/extension.ts
- src/kubernetes.ts
- src/manifest.ts
- src/okteto.ts
> if up is active, use that manifest for down

- package-lock.json
- package.json
- src/extension.ts
- src/okteto.ts
- src/ssh.ts
fixes #3 , depends on https://github.com/okteto/okteto/pull/420
> dynamic port

- package-lock.json
- package.json
- src/extension.ts
- src/manifest.ts
- src/okteto.ts
- src/ssh.ts
- webpack.config.js
- Adds an install command
- Prompt to install if okteto is missing and then continue with the command
fixes #2
> install if missing

- src/okteto.ts
> set the CWD of the okteto terminal

- src/extension.ts
> Show our own picker based on okteto.yml's found in workspace's file tree

- src/extension.ts
> tell the user to create a manifest first

- CHANGELOG.md
- package-lock.json
- package.json
- src/telemetry.ts
Fixes #79 
This will give us more visibility on errors in vscode
> Track releases with sentry

- CHANGELOG.md
- package.json
- src/extension.ts
- src/kubernetes.ts
- src/okteto.ts
> customize kubeconfig

- CHANGELOG.md
- package.json
- src/okteto.ts
> require okteto 1.8.0

- src/okteto.ts
> gitBash should be off by default

- CHANGELOG.md
- package-lock.json
- package.json
- src/okteto.ts
update okteto to 1.8.9, and dependencies to latest major version available
> Upgrade major dependencies

- src/extension.ts
- src/okteto.ts
> stop monitor interval on down

- .github/workflows/nodejs.yml
- README.md
> link to docs on the current branch

- CHANGELOG.md
- package.json
- src/okteto.ts
> update to 1.8.13

- CHANGELOG.md
- package-lock.json
- package.json
- src/okteto.ts
> update to okteto 1.8.16

- package.json
- src/okteto.ts
> settings to specify extra arguments in okteto up

- CHANGELOG.md
- package-lock.json
- package.json
- src/okteto.ts
- src/ssh.ts
> fixes for 0.2.0

- src/okteto.ts
Install the binary based on the OS and ARCH
> support arm binary

- CHANGELOG.md
- src/okteto.ts
> handle $HOME paths with spaces

- package-lock.json
- package.json
To fix a vulnerability reported by dependabot
> update markdown-it to v12

- .github/workflows/codeql-analysis.yml
- package-lock.json
- package.json
This is to support pre-releases.
> update to vsengine 1.63

- CHANGELOG.md
- package-lock.json
- package.json
- src/extension.ts
- src/okteto.ts
This is a temporary solution. It will execute the command on a terminal, instead of in the background. The user still needs to close the terminal, which is not ideal, but can't think of a better option at the moment.
> fix init command

- CHANGELOG.md
- package.json
- src/okteto.ts
> remove quotes from up path since it's breaking windows

- src/okteto.ts
Signed-off-by: Javier López Barba <javier@okteto.com>
@rberrelleza is there any other lines of code that should be changed?
> upgrade cli version to 2.3.3

- src/extension.ts
- src/manifest.ts
- src/test/suite/artifacts/legacy-manifest.yaml
- src/test/suite/artifacts/simple-manifest.yaml
- src/test/suite/manifest.test.ts
> add manifest parsing test

- src/extension.ts
> pass the correct URI when connecting to the remote SSH session

- src/extension.ts
This will also autoselect if there's a single `okteto.yml` or `okteto.yaml` in the folders
> Include files with the "okteto-" prefix in the search

- CHANGELOG.md
- package-lock.json
- package.json
- src/extension.ts
- src/manifest.ts
- src/okteto.ts
- src/test/suite/artifacts/manifest-workdir.yaml
- src/test/suite/artifacts/simple-manifest.yaml
- src/test/suite/manifest.test.ts
> ask for the manifest when deploy/destroy

- CHANGELOG.md
- package-lock.json
- package.json
- src/extension.ts
- src/okteto.ts
- src/telemetry.ts
> Update to Okteto 2.11
